[package]
name = "craft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
home = "0.5.5"
log = "0.4.18"
simplelog = "0.12.1"
